# Helix config
# Keep in ~/.config/helix/config.toml

theme = 'ayu_dark'

[editor]
line-number = "relative"

[keys.normal]
# Hit Esc to deselect selections and multiple cursors
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
# Different cursors for normal and insert modes
insert = "bar"
